dist: trusty
sudo: required
language: python
# The travis Python version is unrelated to the version we build and test
# with.  This is set with the MB_PYTHON_VERSION variable.
python: 3.6
services: docker

env:
  global:
    # directory containing the project source
    - REPO_DIR=.
    # pip dependencies to _build_ project
    # - BUILD_DEPENDS="..."
    # pip dependencies to _test_ project
    - TEST_DEPENDS="tox"
    - PLAT=x86_64
    - UNICODE_WIDTH=32
    - TWINE_USERNAME="anthrotype"
    - secure: yo4TaY6Ezbc1o00OxZm2mXukNLp2BSrcsiwyuOJuASAly/aomrU9T042/RUg3MFhTr0z1fRWuNyFhniTi3Nsj/+IkPei/LBE57ewb1z42tRNfgokcrQC9PEly92suxLkjPjEYURLcVFH3ZsKleL1ysZKnmlcG4WI8X9zoQzkiC+iZdtiQv375J4Ynf4cixAvCiKQ1k7ZxOsfo5oxzY2kZGMHpRV+OSPZpbC0ozpodng096I84oPP/Ium573n7QDSrniY5MxIuhIsW4sLd2zb17+lyQeyKLrZiTHebbYVtTcX+2bt46+0+2CaakRbb4Tsq7sfzMa/yEqAIc5jQEsb5CTdYKvUvjnqTN5bdqNMJCq75TLkCf+k9Fil+e27ghSh2fv5+fDFJPMenjvwtCPHOEXFGdPJ2Q5dm6jSx81bKPMB/7TIzm0yRHdfQ9iAukgZ9SO6XXYmUfxgS7EyXK24WtqPZb0WQdJ74aXhxfQKxrvUDbJqBadTtWW6mkfLrcjinjCM0NpyR5+9u3SE5DA/Qn5+F65eqlJGYylJuBYHHOVMrNZT02rwIHQi5riijW+kQuAVLgWos31/8ZhEXUiy2LfLFgTMEp6y+nLoQKHHlB6hrkMULc2yuo5ZYM4UzuZd8sKeVgxBIKC9ZLkqK4Dfxpze2tT0pSNBsldfWP+EjiM=

matrix:
  fast_finish: true
  exclude:
    # Exclude the default Python 3.6 build
    - python: 3.6
  include:
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
        - BUILD_SDIST=true
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.7

cache: pip

before_install:
  - source multibuild/common_utils.sh
  - source multibuild/travis_steps.sh
  - before_install

install:
  - build_wheel $REPO_DIR $PLAT

script:
  - install_run $PLAT

after_success:
  # If it's a tagged commit, upload sdist and wheel packages to PyPI.
  - |
    if [ -n "$TRAVIS_TAG" ] && [ "$TRAVIS_REPO_SLUG" == "googlefonts/fontval-python" ]; then
        pip install --upgrade twine
        twine upload wheelhouse/font_validator*.whl
        if [ "$BUILD_SDIST" == true ]; then
            pip install --upgrade setuptools setuptools_scm
            python setup.py sdist
            twine upload dist/*.tar.gz
        fi
    fi
